version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - OAuth2__GitHub__ClientId=${OAuth2__GitHub__ClientId}
      - OAuth2__GitHub__ClientSecret=${OAuth2__GitHub__ClientSecret}
    networks:
      - app_network
    command: >
      bash -c "dotnet ef database update && dotnet WebApi.dll"

volumes:
  postgres_data:

networks:
  app_network: