services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./WebApi:/app/WebApi                     # Montowanie katalogu WebApi
      - ./Application:/app/Application            # Montowanie katalogu Application
      - ./Infrastructure:/app/Infrastructure                    # Montowanie katalogu WebApi do /app/WebApi w kontenerze
      - ./Domain:/app/Domain
    working_dir: /app/WebApi
    command: >
      sh -c "dotnet tool install --global dotnet-ef &&
             /root/.dotnet/tools/dotnet-ef database update"

volumes:
  postgres_data: